module.exports = {
  legals: {
  	"Privacy Policy": "Our privacy policy explains how information is collected, used and disclosed by Prevention Health Labs, Inc. (“we”, “us”) with respect to your access and use of Prevention Health Labs, Inc.’s services. When we use the term “Personal Information” in this document, we mean any information that can be used to contact or identify you (such as your name or email address, or your medication list in combination with other information that identifies you).",

  	"Is Registration Necessary?": "Registration is not required to use , however registering does enable you to access your account information on multiple devices. Registering also enables you to recover your information in the event you change mobile phones or reinstall the application on your mobile device. If you choose not to register, we will assign a unique identifier (“UID”) to your device in order to send you medication reminders, notices or other messages, and to provide appropriate content each time you use the services. If you download the services to your mobile device, use it for some time, delete it and then reinstall it, we would create a new UID for you at the time of the reinstall. This means that we would not associate the user with the previous UID and would not show your previous history in the service. If you are an unregistered user who has disabled push notifications, you acknowledge and agree we may not be able to reach you and send you any messages until after your return to Prevention Health Labs, Inc..",

  	"What Information Do We Collect": "If you decide to complete our registration process, send us an email or post information or other content to Prevention Health Labs, Inc., we collect Personal Information from you, such as your name, email address and phone number, as well as certain non-identifying information, like information related to medications or supplements you are taking and your individual preferences.\n\nWe also collect and store any content that you upload, download or access via Prevention Health Labs, Inc., which may include Personal Information about you (including pictures of your prescription or over the counter medication that you decide to upload). If you use Prevention Health Labs, Inc. for a period of time before completing the registration process, we will retain any information in your account and add such information to the information provided during the registration process.\n\nIf you download Prevention Health Labs, Inc. in connection with a program offered by a Benefit or Healthcare Provider and enter an activation code provided to you by your Benefit or Healthcare Provider, your Benefit or Healthcare Provider may provide us Personal Information about you, such as your medication list and refill reminders for us to pass on to you.\n\nWe may automatically collect certain information when you use Prevention Health Labs, Inc., such as Internet Protocol (IP) address (if using a browser), operating system, the browser type, the address of a referring site and your activity on Prevention Health Labs, Inc.. This information is not treated as Personal Information unless we combine it with or link it to any of the personally identifiable information mentioned above. As with many other sites, we may also use “cookies” or web beacons. These are small files that your browser places on your computer. We may use both session cookies and persistent cookies to better understand how you interact with our services, to monitor aggregate usage by our users and web traffic routing on our services, and to improve our services. Most Internet browsers automatically accept cookies. You can instruct your browser, by editing its options, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. In addition, some third parties that we work with (e.g. Kiss Metrics and other technologies used to evaluate the effectiveness of marketing programs) may use their proprietary technologies to analyze your use of Prevention Health Labs, Inc.. Note that this Privacy Policy covers only the use of cookies and other similar technologies by us, and does not cover the use of third-party technologies.",

  	"How Do We Use The Information We Collect": "We use the information collected through Prevention Health Labs, Inc. (including Personal Information) for the following purposes:\n\n* to provide our services, including by providing information such as drug or supplement reminders or drug interactions;\n* to respond to your emails, submissions, questions, comments, requests, and complaints and provide customer service;\n* to monitor and analyze usage and trends, and to increase the functionality and user friendliness of our services;\n* to provide content or features that match your profile or interests, including advertisements and other marketing material; for instance, if you have entered a drug associated with high blood pressure we may send you a coupon or offer for new low sodium foods, or if you accumulate points we may send you a gift card from a commercial retailer;\n* to send you confirmations, updates, security alerts, administrative messages and otherwise facilitate your use of, and our administration and operation of, our services;\n* and for any other purpose that is communicated to you when we collect the information. \n\nWe may receive remuneration from third parties for communicating with your about their products or services, or for providing you with promotional items from them.",

  	"What Information Do We Share With Third Parties?": "We will not share the Personal Information we have collected from you, except as described below:\n\n* we may share your information, including Personal Information, with service providers who have a contractual relationship with us in connection with the operation of our site or our services (these service providers have access to your Personal Information only to perform services on our behalf and are obligated not to disclose it or use it for any other purposes);\n* if you download Prevention Health Labs, Inc. in connection with a program offered by a Benefit or Healthcare Provider, enter an activation code provided to you by the Benefit or Healthcare Provider or otherwise authenticate to a Benefit or Healthcare Provider in the app, we may provide Personal Information about you to the Benefit or Healthcare Provider, including data related to your use of, and interaction with, Prevention Health Labs, Inc.. The Benefit or Healthcare Provider may be able to associate the Personal Information we provide with you;\n * we may share aggregated information with third parties for industry analysis, demographic profiling and other similar purposes;\n * when you give us your consent to do so, including if we notify you that the information you provide will be shared in a particular manner and you provide such information;\n * when we believe in good faith that we are lawfully authorized or required to do so or that doing so is reasonably necessary or appropriate to comply with the law or legal processes or respond to lawful requests or legal authorities, including responding to lawful subpoenas, warrants or court orders;\n* to enforce or apply our privacy policy, our terms of use or our other policies or agreements, and to investigate misuse of our systems;\n * and in connection with, or during negotiations of, any merger, sale of company assets, financing or acquisition, or in any other situation where Personal Information may be disclosed or transferred as one of our business assets. \n\n We may receive remuneration from third parties for sharing your Personal Information with them in the circumstances described above. \n\n We are not responsible for the actions of service providers or other third parties, nor are we responsible for any additional information you provide directly to any third parties.",

  	"Links To Other Sites Or Applications": "Prevention Health Labs, Inc. may contain links to other sites or applications. Any information you provide on those sites or applications is provided directly to the owner of that site or application and is subject to that party's privacy policy. Our privacy policy does not apply to such sites, and we are not responsible for the content or privacy and security practices and policies of those sites.",

  	"Is My Personal Information Protected By HIPPA": "The Personal Information that you enter into our system is not protected by HIPAA (the Health Insurance Portability and Accountability Act of 1996). HIPAA protects health information held by or on behalf of your health care provider or health plan. When you enter Personal Information into Prevention Health Labs, Inc. we hold it on our own account. However, if you register with an activation code provided to you by your Benefit or Healthcare provider or otherwise access your Benefit or Healthcare provider account from within Prevention Health Labs, Inc., we may receive information about you from your Benefit or Healthcare Provider, such as your medication list. If your Benefit or Healthcare Provider is covered by HIPAA, the information it provides us will generally be protected, and we will use and disclose it only as permitted by our agreement with your Benefit or Healthcare Provider, or as required by law, or as authorized by you.",

  	"What Steps Do We Take To Protect Your Information Online?": "We are very concerned with safeguarding your information and employ reasonable measures to do that. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, while we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.",

  	"Accessing and Modifying Your Information": "If you have an account, you can access and modify the Personal Information (that you provided to us) that is associated with your account. You may “opt out“ of receiving marketing or promotional emails or other messages from us by changing your account preferences or by following the instructions in those messages. Note that, even if you opt out of these communications, you may still receive messages from us regarding the administration of your Account and your use of our services.\n\nWhether you are a registered or unregistered Prevention Health Labs, Inc. user, you can request to delete your Personal Information. If you are an unregistered Prevention Health Labs, Inc. user, you may select the “Delete My Data” option in the Settings screen of the mobile application. If you are a registered user you can request to delete your Personal Information you have made available by contacting us and requesting that your Account be deleted. We will take steps to delete your Personal Information as soon as is practicable, but some information may remain in archived/backup copies for our records and as otherwise required by law. If you registered with an activation code provided to you by your Benefit or Healthcare Provider or otherwise access your Benefit or Healthcare provider account from within Prevention Health Labs, Inc., we may have shared your Personal Information with your Benefit or Healthcare Provider. We are unable to delete information in the files of your Benefit or Healthcare Provider.\n\nPlease note that if you decide to have your Personal Information deleted, Prevention Health Labs, Inc. may retain any data related to your Prevention Health Labs, Inc. history in aggregate form, and use and share such aggregate data for its business purposes. Please also note that if you delete our app from your mobile device, we may retain the Personal Information and content in your account, in case you want to reactivate your account at some point in the future.",

  	"International Users": "If you are located outside the United States and choose to provide information to us, we may transfer your information to the United States and process it there (or any other country where we operate). By using Prevention Health Labs, Inc., you consent to the collection, transfer, use, storage and disclosure of your information as described in this privacy policy.",

  	"Our Policy Toward Children": "We do not knowingly collect Personal Information from children under 13. If we learn that we have collected Personal Information of a child under 13, we will take steps to delete such information from our files as soon as possible.",

  	"Changes": "Any information that is collected is subject to the privacy policy in effect at the time such information is collected. We may, however, modify and revise our privacy policy from time-to-time. If we make any material changes to this policy, we will notify you of such changes by posting them on Prevention Health Labs, Inc. or by sending you an email or other notification or message (including push notifications and in-app news notices), and we will indicate when such changes will become effective. By continuing to access or use Prevention Health Labs, Inc. after those changes become effective, you are agreeing to be bound by the revised policy.",

  	"Questions?": "Please contact us if you have any questions about our privacy policy. \n\n Effective: September 2, 2016"

  }
}